### ISSUE TITLE
DOI-Prefix aktualisieren?

### ISSUE THREAD

**Issue by katrinleinweber** [nichtich/RDF-NS#23]
Ebenso wie in https://github.com/hshdb/hshdb2014/pull/2, aber hier ist mir nicht klar, ob [`http://dx.doi.org/` in `share/prefix.cc`](https://github.com/nichtich/RDF-NS/blob/61e6679b439ab5f9e47b6d7a40c7ed6fc028e068/share/prefix.cc#L2103) der Detektion dient, oder daraus neue Links erzeugt werden.

**Comment by nichtich** [comment]
solved
